<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REGISTER_confirmpass</name>
   <tag></tag>
   <elementGuidId>b569a98e-7ae6-4a77-8c0e-7ad7514c7679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmpass</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmpass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Confirm Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2b5700e-a6ac-426f-b99f-509edf811dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>547e3120-6d7a-4ec5-bd67-23cb2852b58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmpassword</value>
      <webElementGuid>534e3754-f30d-4ed9-8cea-ff5685a3a770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmpass</value>
      <webElementGuid>dc02110b-0983-44c5-8e8e-ba63605b0b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>784b213e-e33a-44ef-a526-ddffc2ec6595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>62b07d29-89b0-4b97-8e40-34279a0c0723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmpass&quot;)</value>
      <webElementGuid>f7aa51de-dd69-4e7d-bfba-d9bbe8ecdcd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmpass']</value>
      <webElementGuid>587ecbe3-bca8-4095-8760-faf10be233b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>aa5c7ece-cac2-4adc-bee7-aef514567c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirmpassword' and @id = 'confirmpass' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>4862acd2-6584-41cc-912d-5fd9629fab28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
